airport api
shoshaam/planes-tracking pull request #3
Opened 2021-12-13 13:10 UTC by shoshaam

2021-12-13 17:59 UTC, artsiom-kotau requested changes

2021-12-13 17:59 UTC, artsiom-kotau commented on src/main/java/AirportServlet.java
> +    private final AirportService service = new AirportService();
используешь конкретную имплементацию вместо интверфейсов

2021-12-13 17:59 UTC, artsiom-kotau commented on src/main/java/AirportServlet.java
> +        JsonObject json = new JsonObject();
а если полей будет больше чем 3, например 20 или 40

2021-12-13 17:59 UTC, artsiom-kotau commented on src/main/java/AirportDAO.java
> +            e.printStackTrace();
проглатывание ошибки

2021-12-13 17:59 UTC, artsiom-kotau commented on src/main/java/AirportServlet.java
> +        JsonObject json = new JsonObject();
так же есть проблема, что сериализация может быть изменена на другой формат либо изменится библиотека

2021-12-15 17:09 UTC, artsiom-kotau requested changes

2021-12-15 17:09 UTC, artsiom-kotau commented on src/main/java/ServiceCreator.java
> +public interface ServiceCreator {
это прям круто, но пока рано)
Используй статический метод для создания инстансов

2021-12-15 17:09 UTC, artsiom-kotau commented on src/main/java/SerializerCreator.java
> +public interface SerializerCreator {
смотри ниже

2021-12-15 17:09 UTC, artsiom-kotau commented on src/main/java/JsonSerializer.java
> +        Gson gson = new GsonBuilder()
Gson gson - может быть полем класса

2021-12-15 17:09 UTC, artsiom-kotau commented on src/main/java/AirportService.java
> +    Object getAll();
почему Object, а не коллекцию

2021-12-15 17:09 UTC, artsiom-kotau commented on src/main/java/AirportService.java
> +    Object getById(int id);
почему  не Airport ?

2021-12-15 17:09 UTC, artsiom-kotau commented on src/main/java/AirportInfoService.java
> +        return 10;
почему не объект список Airport ?

2021-12-15 17:09 UTC, artsiom-kotau commented on src/main/java/AirportInfoService.java
> +    public Object getById(int id){
Airport

2021-12-15 17:09 UTC, artsiom-kotau commented on src/main/java/AirportInfoCreator.java
> +public class AirportInfoCreator implements ServiceCreator{
можно использовать статический метод для создания

2021-12-15 17:09 UTC, artsiom-kotau commented on src/main/java/AirportServlet.java
> +        ServiceCreator scr = new AirportInfoCreator();
есть для этого подходящий метод в сервлете

2021-12-16 13:48 UTC, artsiom-kotau requested changes

2021-12-16 13:48 UTC, artsiom-kotau commented on src/main/java/Airport.java
> +    int id;
Объект

2021-12-16 13:48 UTC, artsiom-kotau commented on src/main/java/AirportInfoCreator.java
> +        return new AirportInfoService();
закэшировать

2021-12-16 13:48 UTC, artsiom-kotau commented on src/main/java/AirportService.java
> +    ArrayList getAll();
использовать интерфейс

2021-12-16 13:48 UTC, artsiom-kotau commented on src/main/java/AirportInfoService.java
> +        ArrayList<Airport> airports = new ArrayList<>();
использовать интерфейс

2021-12-16 13:48 UTC, artsiom-kotau commented on src/main/java/AirportInfoService.java
> +public class AirportInfoService implements AirportService{
указать, что Mock

2021-12-16 13:48 UTC, artsiom-kotau commented on src/main/java/AirportInfoService.java
> +        return new Airport(1,"JND55DS", "Minsk");
должен быть реальный поиск

2021-12-16 13:48 UTC, artsiom-kotau commented on src/main/java/AirportServlet.java
> +        Object queryResult = receiveInformation(request, service);
учесть, что объект не найден
и вернуть 404 ошибку

2021-12-16 13:48 UTC, artsiom-kotau commented on src/main/java/JsonSerializerCreator.java
> +        return new JsonSerializer();
закэшировать

2021-12-17 15:59 UTC, artsiom-kotau requested changes

2021-12-17 15:59 UTC, artsiom-kotau commented on src/main/java/AirportService.java
> +    Collection getAll();
используй дженерики <>

2021-12-17 15:59 UTC, artsiom-kotau commented on src/main/java/AirportService.java
> +    Airport getById(Long id) throws ElementNotFoundException;
почему ты решила использовать checked exception?

2021-12-20 16:28 UTC, artsiom-kotau requested changes

2021-12-20 16:28 UTC, artsiom-kotau commented on src/main/java/AirportService.java
> +    Airport getById(Long id) throws ElementNotFoundException;
Optional<Airport>

2021-12-20 16:28 UTC, artsiom-kotau commented on src/main/java/AirportServlet.java
> +    private Object receiveInformation(HttpServletRequest request, AirportService service) throws ElementNotFoundException {
разделить на 2 метода

2021-12-20 16:28 UTC, artsiom-kotau commented on src/main/java/MockAirportService.java
> +    ArrayList<Airport> airports;
Map

2021-12-20 16:28 UTC, artsiom-kotau commented on src/main/java/AirportService.java
> +    Map<Long, Airport> getAll();
List<Airport>

2021-12-20 16:28 UTC, artsiom-kotau commented on src/main/java/MockAirportService.java
> +    public Map<Long, Airport> getAll(){
List<Airport>

2021-12-20 16:28 UTC, artsiom-kotau commented on src/main/java/AirportServlet.java
> +        String jsonQueryResult = receiveInformation(request);
rework

for list separate logic
for single result also separate

2021-12-26 17:55 UTC, artsiom-kotau requested changes

2021-12-26 17:55 UTC, artsiom-kotau commented on src/main/java/AirportServlet.java
> +                    e.printStackTrace();
прокинуть экзепшен выше

2021-12-26 17:55 UTC, artsiom-kotau commented on src/main/java/RealAirportService.java
> +    private static DAO<Airport> dao = new MockAirportDAO();
как мы сможем для этого сервиса изменить имплементацию дао, не меняя код в этом сервисе?

2021-12-28 10:22 UTC, artsiom-kotau requested changes

2021-12-28 10:22 UTC, artsiom-kotau commented on src/main/java/RealAirportService.java
> +    private static Map<Long, Airport> airports = dao.getAll();
т.е. если в процессе у нас аэропортов станет больше, то мы об этом никогда не узнаем?

2021-12-28 10:22 UTC, artsiom-kotau commented on src/main/java/DAO.java
> +    Map<Long, T> getAll();
почему Map?
и куда делся поиск по id?

2022-01-11 14:24 UTC, AlRezz approved these changes

2022-01-13 11:01 UTC, AlRezz approved these changes

2022-01-16 17:48 UTC, AlRezz approved these changes

2022-02-04 11:33 UTC, AlRezz approved these changes

2022-02-09 08:11 UTC, AlRezz approved these changes

2022-02-15 10:56 UTC, merged